name: release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: perl-libwin32/.github/release-action@v2
        with:
          version-file: Win32.pm
          dist-name: Win32
