name: release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: perl-libwin32/.github/release-action@v2
        with:
          version-file: Win32.pm
          dist-name: Win32
